[mypy]
python_version = 3.11
ignore_missing_imports = True
implicit_optional = True
check_untyped_defs = False
disable_error_code = arg-type,assignment,var-annotated,union-attr,return-value,import-untyped,import-not-found,attr-defined
